### ISSUE TITLE
Metamask Transactions Error

### ISSUE THREAD

**Issue by Gbanks2230** [MetisProtocol/metis-testnet-token#5]
Users face Json-RPC errors while trying to confirm transactions on Metamask but this get fixed sometimes when users manually increase the gas limit to an higher price before confirming the transaction, so i would love the team to help users fix this issue because some users dont know how to fix this issue manually . Thank you
![IMG_1385](https://github.com/MetisProtocol/metis-testnet-token/assets/138335119/b9188a4f-e3e7-4510-b0d9-dc1879ff3fac)

**Comment by ericlee42** [comment]
I will forward it to the dev team
